dist: trusty
sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - liborc-0.4-dev
      - libglib2.0-dev
      - libxml2-dev

matrix:
  allow_failures:
    - rust: nightly

script:
    - rustc --version
    - cargo build --all
    - cargo build --all --all-features

before_install:
- curl -L https://people.freedesktop.org/~slomo/gstreamer.tar.gz | tar xz
- sed -i "s;prefix=/root/gstreamer;prefix=$PWD/gstreamer;g" $PWD/gstreamer/lib/pkgconfig/*.pc
- export PKG_CONFIG_PATH=$PWD/gstreamer/lib/pkgconfig
- export GST_PLUGIN_SYSTEM_PATH=$PWD/gstreamer/lib/gstreamer-1.0
- export PATH=$PATH:$PWD/gstreamer/bin
