[options]
girs_dir = "gir-files"
library = "GstVideo"
version = "1.0"
min_cfg_version = "1.0"
target_path = "gstreamer-video-sys"
work_mode = "sys"

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
    "GstBase",
]
