[options]
girs_dir = "gir-files"
library = "GstBase"
version = "1.0"
min_cfg_version = "1.0"
target_path = "gstreamer-base-sys"
work_mode = "sys"

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]
