[options]
girs_dir = "gir-files"
library = "GstNet"
version = "1.0"
min_cfg_version = "1.0"
target_path = "gstreamer-net-sys"
work_mode = "sys"

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
]

[external_libraries]
gstreamer="Gst"
