[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "1.0"
libc = "0.2"
glib-sys = "0.6"
gobject-sys = "0.6"

[dependencies.gstreamer-sys]
path = "../gstreamer-sys"
version = "0.5"

[dependencies.gstreamer-audio-sys]
path = "../gstreamer-audio-sys"
version = "0.5"

[dependencies.gstreamer-video-sys]
path = "../gstreamer-video-sys"
version = "0.5"

[features]
v1_2 = []
v1_4 = ["v1_2"]
v1_6 = ["v1_4"]
v1_8 = ["v1_6"]
v1_10 = ["v1_8"]
v1_12 = ["v1_10"]
v1_14 = ["v1_12"]
dox = []

[lib]
name = "gstreamer_pbutils_sys"

[package]
build = "build.rs"
links = "gstpbutils-1.0"
name = "gstreamer-pbutils-sys"
version = "0.5.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
description = "FFI bindings to libgstpbutils-1.0"
homepage = "https://gstreamer.freedesktop.org"
keywords = ["ffi", "gstreamer", "gnome", "multimedia"]
repository = "https://github.com/sdroege/gstreamer-sys"
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "sdroege/gstreamer-sys", branch = "master" }
