[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
libc = "0.2"
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = {  git = "https://github.com/gtk-rs/sys" }
gio-sys = {  git = "https://github.com/gtk-rs/sys" }

[dependencies.gstreamer-sdp-sys]
path = "../gstreamer-sdp-sys"

[dependencies.gstreamer-sys]
path = "../gstreamer-sys"

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"

[features]
dox = []
v1_2 = []
v1_2_1 = ["v1_2"]
v1_4 = ["v1_2_1"]
v1_6 = ["v1_4"]
v1_8 = ["v1_6"]
v1_10 = ["v1_8"]
v1_12 = ["v1_10"]
v1_14 = ["v1_12"]

[lib]
name = "gstreamer_rtsp_sys"

[package]
build = "build.rs"
links = "gstrtsp-1.0"
name = "gstreamer-rtsp-sys"
version = "0.6.0"
authors = ["Mathieu Duponchelle <mathieu@centricular.com>", "Sebastian Dröge <sebastian@centricular.com>"]
description = "FFI bindings to libgstrtsp-1.0"
homepage = "https://gstreamer.freedesktop.org"
keywords = ["ffi", "gstreamer", "gnome", "multimedia"]
repository = "https://github.com/sdroege/gstreamer-sys"
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "sdroege/gstreamer-sys", branch = "master" }
