[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.8"
glib-sys = "0.3"
gobject-sys = "0.3"
libc = "0.2"

[features]
v1_0_10 = []
v1_10 = ["v1_8"]
v1_12 = ["v1_10"]
v1_2 = ["v1_0_10"]
v1_2_3 = ["v1_2"]
v1_4 = ["v1_2_3"]
v1_6 = ["v1_4"]
v1_8 = ["v1_6"]

[lib]
name = "gstreamer_sys"

[package]
build = "build.rs"
links = "gstreamer-1.0"
name = "gstreamer-sys"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
description = "FFI bindings to libgstreamer-1.0"
homepage = "https://gstreamer.freedesktop.org"
keywords = ["ffi", "gstreamer", "gnome", "multimedia"]
repository = "https://github.com/sdroege/gstreamer-sys"
license = "MIT"
